### ISSUE TITLE
Could you add HSET command

### ISSUE THREAD

**Issue by glikoz** [dingmaotu/mql4-redis#1]
Your great job is working, could you add HSET command

**Comment by glikoz** [comment]
Are redis commands sync? or async?

**Comment by dingmaotu** [comment]
@glikoz Thank you. It's glad to know this work helps other people.

I will try to add more commands (including hash commands) soon. This will make the library more user friendly. Actually, the library supports any redis command by using `command` and `appendCommand` methods in RedisContext.mqh, but you need to handle result parsing and error handling by yourself. In the RedisSimple.mqh module, I showed some examples of wrapping low level commands to high level ones.

The redis commands are sync. The reason is that, though we can make async calls in dll, I did not find any way to call back into a mt4 program. So you can only execute code in dlls in an async callback, which is not particularly useful. Sending custom events to mt4 programs is a good idea to try, but you still can not call `EventChartCustom` in your dll. I have not yet found a way to send custom events to mt4 in C/C++. But I will try since I want this library to be complete.

**Comment by glikoz** [comment]
Hi dingmaotu, thx for your response. I Think async architecture could be achieved by OnTimer method.
You can check async response in OnTimer method.

**Comment by dingmaotu** [comment]
@glikoz I once tried sending wm_timer events from dll to OnTimer and it worked. The problem is that I can not receive parameters and I override the original OnTimer functionality, which is kind of intrusive. OnChartEvent is a better choice as it is designed to receive various events with parameters. Maybe I need to find out how to pass parameters to the OnTimer event handler, or how to send a MT4_Internal_Message to signal OnChartEvent.

**Comment by glikoz** [comment]
@dingmaotu I think you can take parameters via Redis, for example you can create HashSet in Redis:

"callback:expertAdvisorUniqueId:responseJson" 

You can use this hashset for callback responses, or you can use Redis Pub/Sub approach. 

I tried to use another library but I dont have c++ knowledge: https://github.com/AustenConrad/mql4zmq

If you fork this library and merge it to your project you can create end2end solution for humanity :)

Mt4 Integration with Redis+ZeroMq :)

**Comment by dingmaotu** [comment]
@glikoz 

> Mt4 Integration with Redis+ZeroMq :)

this is definitely the way to go 😄 
mql4zmq is several years old. Maybe I will make a new binding after making the redis binding complete.

For asynchronous events, I implemented a mechanism with WM_KEYDOWN message this weekend. Check it out: https://github.com/dingmaotu/mql4-lib#asynchronous-events

**Comment by glikoz** [comment]
I checked it, but i have serious problem, my expertness is c#, I am not comfortable outside of Visual Studio .Net and C# :(
